use_frameworks!

def common_pods
  pod 'CodeQuickKit', '~> 6.4'
  pod 'XCServerAPI', '~> 5.0'
end

target 'XCServerCoreData' do
  platform :ios, '11.0'
  
  common_pods
end

target 'XCServerCoreDataTests' do
  platform :ios, '11.0'
  
  common_pods
end

